import type { Cloth, ClothId } from './types'

export const CLOTHS: Cloth[] = [
  {
    id: 'prachin',
    name: 'Prachin',
    guj: 'પ્રાચીન',
    note: 'the old traditional garbas',
    material: 'Pichhwai on patola',
    ground: 'light',
    bpm: 96,
    palette: {
      chipBg: '#F2E8D5',
      chipInk: '#7A1D1E',
      ground: '#F2E8D5',
      groundDeep: '#DCCBAB',
      ink: '#14100E',
      accent: '#E2A32D',
      figure: ['#9E2B25', '#1B3A5C', '#9E2B25', '#1F6B4F'],
      pot: '#7A1D1E',
      flame: '#F2B33D',
      flameHot: '#FFE9B0',
      ring: '#C9A227',
      progress: '#9E2B25',
    },
  },
  {
    id: 'sanedo',
    name: 'Sanedo',
    guj: 'સનેડો',
    note: 'bhavai folk, the Barot lineage',
    material: 'Bandhani',
    ground: 'dark',
    bpm: 128,
    palette: {
      chipBg: '#7A1522',
      chipInk: '#F5E7CF',
      ground: '#7A1522',
      groundDeep: '#2A0A10',
      ink: '#F5E7CF',
      accent: '#E8AE33',
      figure: ['#F5E7CF', '#E8557F', '#E8AE33', '#2E7D53'],
      pot: '#2A0A10',
      flame: '#F2B33D',
      flameHot: '#FFE9B0',
      ring: '#D4A93C',
      progress: '#F5E7CF',
    },
  },
  {
    id: 'khelaiya',
    name: 'Khelaiya',
    guj: 'ખેલૈયા',
    note: 'the cassette era, synth and brass',
    material: 'Lurex on georgette',
    ground: 'dark',
    bpm: 120,
    palette: {
      chipBg: '#0E3B32',
      chipInk: '#E7C468',
      ground: '#0E3B32',
      groundDeep: '#071F1B',
      ink: '#F4E3B0',
      accent: '#E7C468',
      figure: ['#C42B6B', '#E0653F', '#7B4B9E', '#2E9E8A'],
      pot: '#C42B6B',
      flame: '#F2B33D',
      flameHot: '#FFE9B0',
      ring: '#D9B45A',
      progress: '#E7C468',
    },
  },
  {
    id: 'indipop',
    name: 'Indipop',
    guj: 'ઇન્ડિપોપ',
    note: 'the Falguni Pathak era',
    material: 'Screen-printed chaniya',
    ground: 'light',
    bpm: 118,
    palette: {
      chipBg: '#F0F1EC',
      chipInk: '#C2126A',
      ground: '#F0F1EC',
      groundDeep: '#D4D8CF',
      ink: '#1C1C1A',
      accent: '#F5A81C',
      figure: ['#E5197F', '#F5A81C', '#3FAE49', '#00A0C6'],
      pot: '#E5197F',
      flame: '#F5A81C',
      flameHot: '#FFE9B0',
      ring: '#E5197F',
      progress: '#C2126A',
    },
  },
  {
    id: 'filmi',
    name: 'Filmi',
    guj: 'ફિલ્મી',
    note: 'garba from Hindi films',
    material: 'Abla and zari',
    ground: 'dark',
    bpm: 146,
    palette: {
      chipBg: '#1A1040',
      chipInk: '#E8B948',
      ground: '#1A1040',
      groundDeep: '#080418',
      ink: '#F2D98A',
      accent: '#E8B948',
      figure: ['#D6285A', '#1E8A6E', '#E8B948', '#5B3FBF'],
      pot: '#3A1030',
      flame: '#E8B948',
      flameHot: '#FFF0C0',
      ring: '#E8B948',
      progress: '#E8B948',
    },
  },
  {
    id: 'fusion',
    name: 'Fusion',
    guj: 'ફ્યુઝન',
    note: 'folk songs, band arrangements',
    material: 'Aari on a contemporary grid',
    ground: 'dark',
    bpm: 132,
    palette: {
      chipBg: '#16283D',
      chipInk: '#00E5C0',
      ground: '#16283D',
      groundDeep: '#0A1420',
      ink: '#E8DCC0',
      accent: '#00E5C0',
      figure: ['#E8DCC0', '#C7573F', '#D9A441', '#8FA98C'],
      pot: '#C7573F',
      flame: '#D9A441',
      flameHot: '#FFF0C8',
      ring: '#E8DCC0',
      progress: '#00E5C0',
    },
  },
  {
    id: 'gujpop',
    name: 'Gujarati Pop',
    guj: 'ગુજરાતી પોપ',
    note: 'current Gujarati pop',
    material: 'Digital print on polyester',
    ground: 'dark',
    bpm: 158,
    palette: {
      chipBg: 'linear-gradient(115deg,#4A1180,#8E1264 55%,#C4245A)',
      chipInk: '#FFFFFF',
      ground: '#3D0F6B',
      groundDeep: '#1A0533',
      ink: '#FFFFFF',
      accent: '#FF6A1F',
      figure: ['#FF2D87', '#00D4FF', '#FFD84D', '#B6FF3C'],
      pot: '#FF2D87',
      flame: '#FFD84D',
      flameHot: '#FFFFFF',
      ring: '#FF2D87',
      progress: '#00D4FF',
    },
  },
  {
    id: 'techno',
    name: 'Techno',
    guj: 'ટેક્નો',
    note: 'club production, folk material',
    material: 'Abla in the dark',
    ground: 'dark',
    bpm: 172,
    palette: {
      chipBg: '#08080C',
      chipInk: '#A93DFF',
      ground: '#08080C',
      groundDeep: '#000000',
      ink: '#E6D6FF',
      accent: '#A93DFF',
      figure: ['#14141C', '#0E0E14', '#181822', '#101018'],
      pot: '#0A0A10',
      flame: '#A93DFF',
      flameHot: '#F0E0FF',
      ring: '#A93DFF',
      progress: '#39E0C8',
    },
  },
]

export function clothById(id: string | null | undefined): Cloth | undefined {
  if (!id) return undefined
  return CLOTHS.find((c) => c.id === id)
}

export function isClothId(id: string): id is ClothId {
  return CLOTHS.some((c) => c.id === id)
}
